# Multiple Linear Regression

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv('marketing_data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Taking care of missing data

In [4]:
dataset = dataset.dropna()

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(len(X))
print(len(y))

4546
4546


In [6]:
X = dataset.iloc[:, :-1].values

## Encoding categorical data

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))


## Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
print(X_test)
print(type(X_test))

[[1.0 0.0 0.0 ... 78.0 24.99209995 4.209574548]
 [0.0 0.0 0.0 ... 66.0 20.43830433 2.097019822]
 [0.0 1.0 0.0 ... 47.0 15.89286029 2.001411881]
 ...
 [0.0 1.0 0.0 ... 38.0 12.60091687 2.97134281]
 [0.0 0.0 1.0 ... 43.0 22.95583839 3.316618583]
 [0.0 0.0 1.0 ... 15.0 3.61889035 0.424484925]]
<class 'numpy.ndarray'>


In [10]:
# Mega = 0.0 1.0 0.0 0.0
# Micro = 0.0 0.0 1.0 0.0
# Nano = 0.0 0.0 0.0 1.0

## Training the Multiple Linear Regression model on the Training set

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [12]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[277.74 277.24]
 [234.89 236.16]
 [167.26 167.72]
 ...
 [135.19 140.14]
 [152.94 153.54]
 [ 53.25  57.13]]


In [13]:
#Prediction and test results are really close

## Example

In [14]:
# Sale prediction when Influencer = Mega, Social media promotion budget(in million) = 4, Radio promotion budget(in million) = 20, TV promotion budget(in million)= 15
y_pred = regressor.predict(np.array([[1.0, 0.0, 0.0, 0.0, 15, 20, 4]]))
np.set_printoptions(precision=2)
print(y_pred.reshape(len(y_pred),1))

[[53.35]]
